### ISSUE TITLE
could you help me on a website?

### ISSUE THREAD

**Issue by zoreu** [Twilight0/script.module.resolveurl.pluginsgr#1]
I have a website and would like to extract the m3u8 link

site: https://topcanais.com/player/aovivo.php?canal=sportv3hd&pasta=mylive
referer: https://topcanais.com/assistir-sportv-3-ao-vivo-24-horas-em-hd-online/

I need a python code to help me get the link

**Comment by Twilight0** [comment]
I don't do feature requests on this repository or external plugins, issue closed.
